config/routes.rb
Rails.application.routes.draw do
  root 'invoices#step1'

  get 'invoices/step1', to: 'invoices#step1', as: :invoices_step1
  post 'invoices/attach_pdf', to: 'invoices#attach_pdf', as: :attach_pdf
  
  post 'invoices/connect_booking', to: 'invoices#connect_booking', as: :connect_booking
  post 'invoices/verify_booking', to: 'invoices#verify_booking', as: :verify_booking
  post 'invoices/add_invoice_details', to: 'invoices#add_invoice_details', as: :add_invoice_details
  post 'invoices/add_line_item', to: 'invoices#add_line_item', as: :add_line_item
  delete 'invoices/:id/remove_line_item', to: 'invoices#remove_line_item', as: :remove_line_item
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :invoices, dependent: :destroy
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :booking, optional: true
  has_many :line_items, dependent: :destroy
  has_one_attached :pdf

  accepts_nested_attributes_for :line_items, allow_destroy: true
  
  validates :pdf, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :invoice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def step1
    @invoice = Invoice.new
  end

  def attach_pdf
    @invoice = Invoice.new(invoice_params)
    @invoice.save

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace('step1_frame', partial: 'invoices/step2', locals: { invoice: @invoice }),
          turbo_stream.update('step_nav', partial: 'invoices/step_nav', locals: { current_step: 2 })
        ]
      end
    end
  end

  def connect_booking
    @invoice = Invoice.find(params[:invoice_id])
    @invoice.update(booking_item: params[:booking_item])

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace('step2_frame', partial: 'invoices/step3', locals: { invoice: @invoice }),
          turbo_stream.update('step_nav', partial: 'invoices/step_nav', locals: { current_step: 3 })
        ]
      end
    end
  end

  def verify_booking
    @invoice = Invoice.find(params[:invoice_id])

    @invoice.update(germany_residence: params[:germany_residence] == "0" ? false : true)
    @line_item = @invoice.line_items.build
    @line_item.save

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace('step3_frame', partial: 'invoices/step4', locals: { invoice: @invoice }),
          turbo_stream.update('step_nav', partial: 'invoices/step_nav', locals: { current_step: 4 })
        ]
      end
    end
  end

  def add_invoice_details
    @invoice = Invoice.find(params[:invoice_id])
    
    @invoice.update(invoice_params)
    
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace('step4_frame', partial: 'invoices/step5', locals: { invoice: @invoice }),
          turbo_stream.update('step_nav', partial: 'invoices/step_nav', locals: { current_step: 5 })
        ]
      end
    end
  end

  def add_line_item
    @invoice = Invoice.find(params[:invoice_id])
    @line_item = @invoice.line_items.build
    @line_item.save

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: 
          turbo_stream.append("line_item_list", partial: "line_items/line_item", locals: { line_item: @line_item })
      end
    end
  end
    
  def remove_line_item
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: 
          turbo_stream.remove("line_item_#{@line_item.id}")
      end
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(
      :pdf,
      :country,
      :vat_number,
      :company_name,
      :invoice_date,
      :invoice_number,
      :street_name,
      :street_number,
      :postal_code,
      :city,
      :has_word,
      line_items_attributes: [:id, :traveler_name, :start_date, :end_date, :description, :category, :quantity, :unit, :price, :vat_rate]
    )
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/invoices/_step2.html.erb
<div class="container">
  <%= turbo_frame_tag "step2_frame" do %>  
    <div class="row">
      <div class="col-md-7">
        <embed src="<%= url_for(@invoice.pdf) %>" width="100%" height="600px" type="application/pdf">
      </div>

      <div class="col-md-5">
        <%= form_with url: connect_booking_path(invoice_id: @invoice.id), local: true, data: { turbo_frame: 'step2_frame' } do |form| %>
          <div class="form-group message">
            <p class="title">Connect the correct booking item ID</p>
            <p class="content">Please lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer tempor eleifend tortor quis vulputate. Integer non felis ac odio imperdiet lobortis id sed erat.</p>
          </div>
          <div class="wrap">
            <p class="title">Connect Booking</p>
            <div class="form-group">
              <%= form.label :booking_item %>
              <%= form.text_field :booking_item, class: "form-control", required: true %>
            </div>
          </div>
          
          <div class="actions next_btn_wrap">
            <%= form.submit 'Go To Next Stop ➜', class: "btn btn-primary mt-3" %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/invoices/_step3.html.erb
<div class="container">
  <%= turbo_frame_tag "step3_frame" do %>  
    <div class="row">
      <div class="col-md-7">
        <embed src="<%= url_for(@invoice.pdf) %>" width="100%" height="600px" type="application/pdf">
      </div>

      <div class="col-md-5">
        <%= form_with url: verify_booking_path(invoice_id: @invoice.id), local: true, data: { turbo_frame: 'step3_frame' }, id: "invoiceForm" do |form| %>
          <div class="form-group message">
            <p class="title">Verify the booking</p>
            <p class="content">Please make sure that all of the following information is correctly shown on the received invoice.</p>
          </div>

          <div class="wrap">
            <p class="title">Location Invoice Company</p>
            <div class="form-group">
              <%= form.check_box :germany_residence, { checked: @invoice.germany_residence }, class: "form-control checkbox-field" %>
              <%= form.label :germany_residence, "The invocing company also resides in Germany" %>
            </div>
          </div>

          <div class="wrap">
            <p class="title">Booking Information</p>
            <div class="form-group">
              <div class="left_div">Name of hotel</div>
              <div class="right_div">Motel One</div>
            </div>
            <div class="form-group">
              <div class="left_div">Name of first traveller</div>
              <div class="right_div">Diana Alfonsi-Pobner</div>
            </div>
            <div class="form-group">
              <div class="left_div">Check-in date</div>
              <div class="right_div">17.04.2024</div>
            </div>
            <div class="form-group">
              <div class="left_div">Check-out date</div>
              <div class="right_div">19.04.2024</div>
            </div>
            <div class="form-group underline"></div>
            <div class="form-group">
              <%= form.check_box :booking_confirmation, { checked: false }, class: "form-control checkbox-field" %>
              <%= form.label :booking_confirmation, "All information above is correctly shown on invoice", class: "checkbox-field" %>
            </div>
          </div>

          <div class="wrap">
            <p class="title">Receiving Company</p>
            <div class="form-group">
              <div class="left_div">Name of company</div>
              <div class="right_div">Klambt Verlag GmbH & Co. Kg</div>
            </div>
            <div class="form-group">
              <div class="left_div">Additional address information</div>
              <div class="right_div">-</div>
            </div>
            <div class="form-group">
              <div class="left_div">Street name</div>
              <div class="right_div">Rotweg.</div>
            </div>
            <div class="form-group">
              <div class="left_div">Postal code</div>
              <div class="right_div">76532</div>
            </div>
            <div class="form-group">
              <div class="left_div">City</div>
              <div class="right_div">Baden-Baden</div>
            </div>
            <div class="form-group">
              <div class="left_div">Country</div>
              <div class="right_div">Germany</div>
            </div>
            <div class="form-group underline"></div>
            <div class="form-group">
              <%= form.check_box :receiving_confirmation, { checked: false }, class: "form-control checkbox-field" %>
              <%= form.label :receiving_confirmation, "All information above is correctly shown on invoice", class: "checkbox-field" %>
            </div>
          </div>

          <div class="actions next_btn_wrap">
            <%= form.submit 'Go To Next Step ➜', class: "btn btn-primary mt-3", id: "submitBtn" %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<!-- JavaScript for Validation -->
<script>
  document.getElementById('invoiceForm').addEventListener('submit', function(event) {
    document.querySelectorAll('.checkbox-field').forEach(function(checkbox) {
      checkbox.classList.remove('is-invalid');
    });

    const bookingConfirmationChecked = document.getElementById('booking_confirmation').checked;
    const receivingConfirmationChecked = document.getElementById('receiving_confirmation').checked;

    let isValid = true;

    if (!bookingConfirmationChecked) {
      const checkbox = document.getElementById('booking_confirmation');
      checkbox.classList.add('is-invalid');
      const label = checkbox.nextElementSibling;
      if (label) {
        label.classList.add('is-invalid');
      }
      isValid = false;
    }

    if (!receivingConfirmationChecked) {
      const checkbox = document.getElementById('receiving_confirmation');
      checkbox.classList.add('is-invalid');
      const label = checkbox.nextElementSibling;
      if (label) {
        label.classList.add('is-invalid');
      }
      isValid = false;
    }

    if (!isValid) {
      event.preventDefault();
    }
  });
</script>

app/views/invoices/_step4.html.erb
<div class="container">
  <%= turbo_frame_tag "step4_frame" do %>  
    <div class="row">
      <div class="col-md-7">
        <embed src="<%= url_for(@invoice.pdf) %>" width="100%" height="600px" type="application/pdf">
      </div>

      <div class="col-md-5">
        <%= form_with url: add_invoice_details_path(invoice_id: @invoice.id), local: true, data: { turbo_frame: 'step4_frame' }, id: "invoiceForm" do |form| %>
          <div class="form-group message">
            <p class="title">Add additional inovice details</p>
            <p class="content">Please transfer all needed inovice information lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum dignissim nulla ipsum.</p>
          </div>

          <div class="wrap">
            <p class="title">Invocing company</p>

            <div class="form-group">
              <%= form.label :country, "Country" %>
              <%= form.select :country, options_for_select([['Germany', 'Germany'], ['Canada', 'Canada']]), {}, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :vat_number, "VAT ID or tax-number" %>
              <%= form.text_field :vat_number, class: "form-control", required: true %>
            </div>
            <div class="form-group">
              <%= form.label :company_name, "Company name" %>
              <%= form.text_field :company_name, class: "form-control", required: true %>
            </div>
            <div class="form-group">
              <%= form.label :invoice_date, "Invoice date" %>
              <%= form.date_field :invoice_date, class: "form-control", value: @invoice.invoice_date, required: true %>
            </div>
            <div class="form-group">
              <%= form.label :invoice_number, "Invoice number" %>
              <%= form.text_field :invoice_number, class: "form-control", required: true %>
            </div>
            <div class="row">
              <div class="form-group col-md-8">
                <%= form.label :street_name, "Street name" %>
                <%= form.text_field :street_name, class: "form-control", required: true %>
              </div>
              <div class="form-group col-md-4">
                <%= form.label :street_number, "Street number" %>
                <%= form.text_field :street_number, class: "form-control", required: true %>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-md-4">
                <%= form.label :postal_code, "Postal Code" %>
                <%= form.text_field :postal_code, class: "form-control", required: true %>
              </div>
              <div class="form-group col-md-8">
                <%= form.label :city, "City" %>
                <%= form.text_field :city, class: "form-control", required: true %>
              </div>
            </div>
            <div class="form-group">
              <%= form.check_box :has_word, { checked: @invoice.has_word }, local: true, class: "form-control checkbox-field" %>
              <%= form.label :has_word, "The invoice has the word 'invoice' on it" %>
            </div>
          </div>

          <%= turbo_frame_tag "line_item_list" do %>
            <%= render partial: 'line_items/line_item', collection: @invoice.line_items, as: :line_item %>
          <% end %>

          <div class="wrap">
            <p class="title">Totals</p>
            <div class="form-group">
              <div class="left_div">Subtotal</div>
              <div class="right_div">2460,14</div>
            </div>
            <div class="form-group">
              <div class="left_div">VAT 7% on 0,0</div>
              <div class="right_div">0,0</div>
            </div>
            <div class="form-group">
              <div class="left_div">VAT 19% on 8,40</div>
              <div class="right_div">172,21</div>
            </div>
            <div class="form-group">
              <div class="left_div title">Total EUR</div>
              <div class="right_div title">2632,35</div>
            </div>
          </div>

          <div class="actions next_btn_wrap">
            <%= form.submit 'Go To Next Step ➜', class: "btn btn-primary mt-3 next_btn" %>
          </div>
        <% end %>

        <%= form_with url: add_line_item_path(invoice_id: @invoice.id), local: true, data: { turbo_frame: 'line_item_list' } do |form| %>
          <%= form.submit '✚ Add Line Item', class: "btn btn-secondary mt-3 add_item_btn" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/invoices/_step5.html.erb
<div class="container">
  <%= turbo_frame_tag "step5_frame" do %>  
    <div class="row">
      <div class="col-md-7">
        <embed src="<%= url_for(@invoice.pdf) %>" width="100%" height="600px" type="application/pdf">
      </div>

      <div class="col-md-5">
        <div class="wrap">
          <p class="title">All Done. Thank you!</p>
          <div class="next_btn_wrap">
            <button id="refresh-button" class="btn btn-primary"><- Go To First Step</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  document.getElementById('refresh-button').addEventListener('click', function() {
    location.reload();
  });
</script>

app/views/invoices/_step_nav.html.erb
<div class="container mt-5">
  <div class="steps">
    <span class="step-label <%= 'active' if current_step == 1 %> <%= 'checked' if current_step > 1 %>"><span class="number"><%= current_step > 1 ? "✓" : "1" %></span>Attach PDF</span>
    <span class="step-label <%= 'active' if current_step == 2 %> <%= 'checked' if current_step > 2 %>"><span class="number"><%= current_step > 2 ? "✓" : "2" %></span>Connect booking item</span>
    <span class="step-label <%= 'active' if current_step == 3 %> <%= 'checked' if current_step > 3 %>"><span class="number"><%= current_step > 3 ? "✓" : "3" %></span>Verify booking</span>
    <span class="step-label <%= 'active' if current_step == 4 %> <%= 'checked' if current_step > 4 %>"><span class="number"><%= current_step > 4 ? "✓" : "4" %></span>Add invoice details</span>
    <span class="step-label <%= 'active' if current_step == 5 %>"><span class="number">5</span>Connect charges</span>
  </div>
</div>

app/views/invoices/step1.html.erb
<%= turbo_frame_tag "step_nav" do %>
  <%= render 'invoices/step_nav', current_step: 1 %>
<% end %>

<div class="container">
  <%= turbo_frame_tag "step1_frame" do %>
      <%= form_with model: @invoice, url: attach_pdf_path, local: true, multipart: true, data: { turbo_frame: 'step1_frame' } do |form| %>
        <% if @invoice.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>
            <ul>
              <% @invoice.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.file_field :pdf, class: "form-control", required: true %>
        </div>
        <div class="actions next_btn_wrap">
          <%= form.submit 'Go To Next Step ➜', class: "btn btn-primary mt-3" %>
        </div>
      <% end %>
  <% end %>
</div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Invoice Processor" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= turbo_include_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/line_items/_line_item.html.erb
<div class="wrap nested-fields" id="line_item_<%= line_item.id %>">
  <p class="title">Line item</p>
  
  <div class="row">
    <div class="form-group col-md-12">
      <label>Name of traveler</label>
      <input class="form-control" type="text" name="invoice[line_items_attributes][<%= line_item.id %>][traveler_name]">
    </div>
    <div class="row">
      <div class="form-group col-md-6">
        <label>Start date</label>
        <input class="form-control" type="date" name="invoice[line_items_attributes][<%= line_item.id %>][start_date]">
      </div>
      <div class="form-group col-md-6">
        <label>End date</label>
        <input class="form-control" type="date" name="invoice[line_items_attributes][<%= line_item.id %>][end_date]">
      </div>
    </div>
    <div class="form-group col-md-12">
      <label>Description</label>
      <input class="form-control" type="text" name="invoice[line_items_attributes][<%= line_item.id %>][description]">
    </div>
    <div class="form-group col-md-12">
      <label>Category</label>
      <select class="form-control" name="invoice[line_items_attributes][<%= line_item.id %>][category]">
        <option value="Category1">Category1</option>
        <option value="Category2">Category2</option>
      </select>
    </div>
    <div class="form-group col-md-12">
      <label>Quantity</label>
      <input step="1" class="form-control" type="number" name="invoice[line_items_attributes][<%= line_item.id %>][quantity]">
    </div>
    <div class="row">
      <div class="form-group col-md-4">
        <label>Unit</label>
        <input class="form-control" type="text" name="invoice[line_items_attributes][<%= line_item.id %>][unit]">
      </div>
      <div class="form-group col-md-4">
        <label>Price</label>
        <input step="0.01" class="form-control" type="number" name="invoice[line_items_attributes][<%= line_item.id %>][price]">
      </div>
      <div class="form-group col-md-4">
        <label>VAT rate</label>
        <select class="form-control" name="invoice[line_items_attributes][<%= line_item.id %>][vat_rate]">
          <option value="Incl. 19%">Incl. 19%</option>
          <option value="Incl. 18%">Incl. 7%</option>
        </select>
      </div>
    </div>
    <div class="form-group col-md-12">
      <%= button_to 'Remove line item', remove_line_item_path(line_item.id), method: :delete, class: "btn btn-danger remove-item remove_btn", data: { turbo_frame: "line_items" } %>
    </div>
  </div>
</div>